name: weathercast
description: A simple Weather App demonstrating Flutter

version: 1.0.3

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mvc_application: ^1.0.3
#    git:
#      url: git://github.com/AndriousSolutions/mvc_application.git

  http:
    #^0.12.0

  equatable:
    #^0.1.0

  ads: #^0.4.2

  #firebase_admob: ^0.9.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/